development:
  adapter: postgresql
  database: capstone_development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
production:
  adapter: postgresql
  database: capstone_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>